### PR TITLE
Avoid crash on paint_active_slot in Blender 2.93

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/ubisoft/mixer/issues/20
Fixes: https://github.com/ubisoft/mixer/issues/18
Fixes: https://github.com/ubisoft/mixer/issues/26

Can someone test?

I don't like the location of key check. Any better designs?

### CODE REVIEW

**Comment by charlesfleche** [comment]
This fix works: tested on Ubuntu 21.04 with blender 2.93.5

**Comment by fire** [comment]
@Celeborn2BeAlive Who can review this and how can I have issues reviewed in a timely manner?

**Comment by rennmaus-coder** [comment]
@fire you should try if this pull request works for you

**Comment by fire** [comment]
@rennmaus-coder does it not work? I tested when I created the pr.

**Comment by rennmaus-coder** [comment]
OK, first I thought you were the one who created the issue, sorry. And no, unfortunately it doesn't work for me. Tomorrow I will edit this post with further information...

**Comment by fire** [comment]
@rennmaus-coder Were you able to get it to work?

**Comment by rennmaus-coder** [comment]
Yeah, I think I just didn't install the Plugin properly, sorry.

**Pull request merged**
